apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-ingress-datacenter
  namespace: haproxy-controller-datacenter
  labels:
    run: haproxy-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
        run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      serviceAccountName: haproxy-service-account-datacenter
      containers:
      - name: ingress-container-datacenter
        image: haproxytech/kubernetes-ingress
        args: 
        - --default-backend-service=haproxy-controller-datacenter/service-backend-datacenter
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1024  
        resources:
          requests:
            memory: "50Mi"
            cpu: "500m"
        livenessProbe: 
          httpGet:
           path: /healthz
           port: 1024         
        env:
        - name: "TZ"
          value: "Etc/UTC"
        - name: "POD_NAME"
          valueFrom: 
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef: 
              fieldPath: metadata.namespace
              
             
             