---
apiVersion: v1
kind: Service
metadata:
    namespace: haproxy-controller-devops
    name: service-backend-devops
spec:
    type: NodePort
    ports:
    - port: 8080
      name: port-backend
      protocol: TCP
      targetPort: 8080
    selector:
       run: ingress-default-backend