---
apiVersion: v1
kind: Service
metadata:
    namespace: haproxy-controller-datacenter
    name: service-backend-datacenter 
    labels:
      run: ingress-default-backend
spec:
    ports:
    - port: 8080
      name: port-backend
      protocol: TCP
      targetPort: 8080
    selector:
       run: ingress-default-backend